Developer-Y/cs-video-courses

- README.md
UBC computer science course based on How to Design Programs book. Teaches design recipes and functional programming.
> added University of British Columbia course SPD1

- README.md
From HN today: https://news.ycombinator.com/item?id=13001068
Each lecture has screencast links.
> Add CS294: Program Synthesis for Everyone

- README.md
From the Fall 2012 to Spring 2015 - also available on YouTube.
> Updated Math course

- README.md
> Added links to Bilkent University Computer Organization course

- README.md
Add links to lectures for the yearly summer school at U of Oregon. Harper, Pfenning, Awoley, Morehouse et al.
> Oregon Programming Languages Summer School videos

- README.md
Prior link was returning a server error. This link takes you to the course page which includes embedded lecture videos.
> Fix link for CS223A - Intro to Robotics

- README.md
Updating 15-721 - Database Systems to from 2016 version to 2017 version
> Updating 15-721 - Database Systems to from 2016 version to 2017 version

- README.md
Fixed the dead link of 14-740 - Fundamentals of Computer Networks. Issue #55
> Fix 14-740 - Fundamentals of Computer Networks (#55)

- README.md
#67 Link broken  [The Probability and Statistics Full Course - YouTube](https://www.youtube.com/playlist?list=PLLssT5z_DsK_WYzNXVjT695FdxRxvlSF8)
> Link Broken The Probability and Statistics Full Course - YouTube

- README.md
#67 Videos made private by Uploader [Statistics 20, Fall 2010 - UC Berkeley](https://www.youtube.com/playlist?list=PLnzPXnz47JdHX8mjs2inYX8Ijrde6mUUS)
> Videos Unavailable Statistics 20, Fall 2010 - UC Berkeley

- README.md
Videos Unavailable [CS 10 The Beauty & Joy of Computing, Spring 2015 - UCBerkeley](https://www.youtube.com/playlist?list=PL-XXv-cvA_iC17q7Pydw_RernkItDJePz)
> Videos Unavailable CS 10 The Beauty & Joy of Computing, Spring 2015 UCB

- README.md
Videos in the Lecture Notes Unavailable [CS 61B - Data Structures, Josh Hug, Spring 2016 - UC Berkeley](http://datastructur.es/sp16/)
> Videos in the Lecture Notes Unavailable CS 61B - Data Structures, Spring 2016 - UC Berkeley

- README.md
Videos Unavailable [CS 162 - Operating Systems and Systems Programming, UC Berkeley](http://cs162.eecs.berkeley.edu/) ([Lectures - YouTube](https://www.youtube.com/playlist?list=PL-XXv-cvA_iBDyz-ba4yDskqMDY6A1w_c))
> Videos Unavailable CS 162 - Operating Systems and Systems Programming, UC Berkeley

- README.md
Misc Section - [Skiena's Computational Finance Lectures](http://www.algorist.com/computational_finance/index.html)
> Remove unavailable link

- README.md
The 61C YouTube playlist was taken down but I found the lectures on InfoCoBuild and there are CS 10 lectures there too.
> Add InfoCoBuild Berkeley lectures

- README.md
6.834J Cognitive Robotics - selected videos lectures.
> Added Cognitive Robotics - MIT OCW

- README.md
Added an introduction to machine learning course from the University at Buffalo.
> Added machine learning course

- README.md
#65 
Updated link to course sit and added videos with slides.
> Updated Computer Networks RPI link

- README.md
* Updated course site and lecture videos for CMPSC 431 Database Management Systems and removed the broken link
* Updated course site and lecture videos for CS 446 Machine Learning and removed the broken link
> CMPSC 431 and CS 446 fixed broken links

- README.md
* Added CSE 331 Introduction to Algorithm Analysis and Design lectures, and homework walkthroughs
* Added CSE 421/521 Introduction to Operating Systems assignment walkthroughs
> CSE 331 and Walkthroughs

- README.md
Added CS-162 Operating Systems and Systems Programming, Spr 2015
> CS 162 Operating Systems and Systems Programming

- README.md
Add CMU 15-445 Introduction to Database Systems
> Add 15-445 ,CMU

- README.md
Remove unavailable link of CS-168 and add an available link from InfoCoBuild
> Update CS-186 available link

- README.md
Added Algorithms by Robert Sedgewick and Kevin Wayne. To be honest, this is the most friendly course that I have seen. Maybe because it needs enrollment on Coursera to see the videos, it's not on your list. I find one available link on Youtube and I really hope it can be added to the list.
> Add COS 226, Algorithms Part 1 and Part 2 on Coursera

- README.md
* Updated some Stanford courses with lecture videos and new course pages
* Added CS106x #73
> Updated Stanford courses

- README.md
* Added new HPI courses not on the list
* Updated HPI iTunes links to course website with videos
> Added new and updated HPI courses

- README.md
Hey @Developer-Y 
just fixing a broken link to CS50.
Cheers!
> Fixing CS50 link

- README.md
Hey @Developer-Y 
just fixing a link.
Cheers!
> Updating course link

- README.md
Add SE and MIS courses from Bauhaus-Uni Weimar, Germany (course language is English, though).
> Add SE courses

- README.md
Removed inaccessible courses: 6.033 MIT and CS24 CalTech
Added new courses: 6.S081 MIT (2020)
> Update course links

- README.md
The following link is invalid:
[Informatics 2C - Software Engineering 2014/15- University of Edinburgh](http://groups.inf.ed.ac.uk/vision/VIDEO/2014/inf2SE.htm)
> Remove invalid link

- README.md
The playlist does not exist anymore on youtube so I have added a new link to another playlist on youtube .
> Fixed MATLAB MOOC link

- README.md
add a more recent version of cs169 UC Berkeley software engineering fall 2019
> add a more recent version of cs169 ucberekeley software engineering fall 2019

- README.md
Realtime System Evaluation and Block chain Development added
> Blockchain patch

- README.md
Machine Learning with graphs is a new field that is transforming ML. Stanford has a course on the same. I found it to be very useful and have added the link. It has 20-1 hour lectures that cover all the topics.
> Added Machine Learning with graphs from Stanford university

- README.md
Although the video is very "old", but it is very suitable for beginners.
> add a very clear course about data structures

- README.md
adding courses modern robotics by northwestern university and aerial
> adding two courses in robotics list

- README.md
This is a deep learning course form Washington University in St. Louis, all video lectures are available on YouTube and code/notes on GitHub.
> Adding T81-558: Applications of Deep Neural Networks

- README.md
fix an unavailable URL of 6.006 MIT to a available one
> Fix an unavailable URL

- README.md
- (Programming and Data Structures with Python, 2021-2022, Sem I) in Data Structures and Algorithms
- (Advanced Machine Learning, 2021-2022, Sem I) in Advanced Machine Learning
> Add 2 courses by Prof. Madhavan Mukund, CMI

- README.md
Adding CS61B Data Structures to Data Structures and Algorithms.
> Adding CS61B Data Structures

- README.md
by Martin Kleppmann from University of Cambridge
> Added Lectures Series for Distributed Computing

- README.md
Functional Programming course taught by [Graham Hutton](http://www.cs.nott.ac.uk/~pszgmh/) from University of Nottingham.
* [Course website](http://www.cs.nott.ac.uk/~pszgmh/pgp.html)
* [Course playlist](https://www.youtube.com/playlist?list=PLF1Z-APd9zK7usPMx3LGMZEHrECUGodd3)
* [Course textbook](http://www.cs.nott.ac.uk/~pszgmh/pih.html)
> Add Functional Programming course (2021) from University of Nottingham

- README.md
I have added an absolutely useful course for Blockchain, Solidity, and Full Stack Web3 Development with JavaScript.
> Update README.md (New Blockchain Course added)

- README.md
This is the newest CS 193p version of the course, with all resources provided from Stanford.
> Update CS 193p course

- README.md
The link for 6.046J under Data Structures and Algorithms was broken so i fixed it.
> Fixed-broken-Link (6.046J)

- README.md
BE5B35APO - Computer Architectures, Spring 2022, Czech Technical University in Prague, Faculty of Electrical Engineering
> BE5B35APO - Computer Architectures, CTU FEE

- README.md
Course name is Offensive Security and Reverse Engineering. Taught at Chaplain University by Ali Hadi
> Added a new course in the security section.

- README.md
- Data structures course
- OS course
Provides all the lecture+discussion videos for both courses
> Add a couple of undergrad courses from UC Davis

- README.md
The
https://www.youtube.com/playlist?list=PL6397E4B26D00A269
Playlist has no longer exists
> The playlist has been removed

- README.md
Added full stack deep learning course
>  Added full stack deep learning course

- README.md
This YouTube course is by a reputed professor from IIT Delhi. This extensive playlists covers major aspects of compilers.
> Add Compiler Design Course

- README.md
> add video at Computer Network section

- README.md
Hello, cs-video-courses Contributor Team!
I've found an immeasurably valuable Deep Learning Course recently. It covers CV, NLP, RL, Multimodal topics in Deep Learning and has over 500 videos!
They are dense, math-filled and are sequenced in order of historical occurrence of described concepts, models - which is also useful. As this not only gives you a necessary theoretical background for deep-diving into more complex DL models, but also gives you a historical understanding of how AI industry developed through years.
I find it necessary to add this entry to your list - hence this PR. 
Thank you for reading this message! I will be happy to see this entry merged!
> Added one Deep Learning Course

- README.md
Hello there. I added CMU 17-445 Software Engineering for AI-Enabled Systems summer 2020, by Christian Kaestner
[Youtube playlist](https://www.youtube.com/playlist?list=PLDS2JMJnJzdkQPdkhcuwcbJpjB84g9ffXl)
[Course page](https://ckaestne.github.io/seai/S2020/)
> Added CMU 17-445

- README.md
Course link: https://www.csa.iisc.ac.in/~vg/teaching/SecurityLectures/
Lectures are freely hosted on Youtube.
> Add Computer Systems Security course by Prof Vinod Ganapathy from IISc

- README.md
Hey there,
I added Zero Knowledge Proofs MOOC, Berkeley RDI Center on Decentralization & AI
> Add UCB ZKP MOOC

- README.md
Alternative Methods: 
1. Alternative YouTube link
2. Archived Lecture (Internet Archive)
3. Lecture Notes & Course Breakdown (Blog)
>  Resolved Issue #347 Added Alternative Resources

- README.md
About the invitation to collaborate on this repository, I am noticing and I am very thankful for that.
> Add UT Austin CS391L (SP25)
